#!/usr/bin/env python3
"""Prints the Homebrew formula for an age-plugin-rypt release.

Usage: homebrew_formula.py VERSION SHA256SUMS [--repository OWNER/NAME] [--base-url URL]

SHA256SUMS is the checksum file the release workflow publishes. The formula
downloads each platform's tarball from that release on GitHub, or from
--base-url when it is given, which is how a formula is tested before a release.
"""

import argparse
import re
import sys
from string import Template

# Homebrew's platform blocks, and the release target that serves each.
PLATFORMS = [
    ("macos", "arm", "aarch64-apple-darwin"),
    ("macos", "intel", "x86_64-apple-darwin"),
    ("linux", "arm", "aarch64-unknown-linux-musl"),
    ("linux", "intel", "x86_64-unknown-linux-musl"),
]

# The test needs no token and no network: `new` and `recipient` never call
# the rypt API. The expected recipient encodes the key id used.
FORMULA = Template('''\
# Generated by the release workflow of https://github.com/$repository.
# Edits here are overwritten by the next release.
class AgePluginRypt < Formula
  desc "Plugin for age that wraps file keys with rypt.dev keys"
  homepage "https://github.com/$repository"
  license any_of: ["MIT", "Apache-2.0"]

  depends_on "age"

$platforms
  def install
    bin.install "age-plugin-rypt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/age-plugin-rypt --version")
    identity = shell_output("#{bin}/age-plugin-rypt new --key 3f2a9c1e-7b4d-4e2a-9f10-6c8d5a2b1e47")
    assert_equal "age1rypt18u4fc8nmf48z48csdjx452c7gu9hx89g\\n",
                 pipe_output("#{bin}/age-plugin-rypt recipient", identity)
  end
end
''')


def read_sums(path):
    """Maps each file name in a sha256sum-format file to its checksum."""
    sums = {}
    with open(path, encoding="utf-8") as lines:
        for number, line in enumerate(lines, 1):
            if not line.strip():
                continue
            fields = line.split(maxsplit=1)
            if len(fields) != 2 or not re.fullmatch(r"[0-9a-f]{64}", fields[0]):
                sys.exit(f"{path}:{number}: not a sha256sum line")
            sums[fields[1].strip().lstrip("*")] = fields[0]
    return sums


def platform_blocks(version, sums, base_url):
    lines = []
    for system in ("macos", "linux"):
        lines.append(f"  on_{system} do")
        for block_system, cpu, target in PLATFORMS:
            if block_system != system:
                continue
            name = f"age-plugin-rypt-v{version}-{target}.tar.gz"
            if name not in sums:
                sys.exit(f"no checksum for {name}")
            lines += [
                f"    on_{cpu} do",
                f'      url "{base_url}/{name}"',
                f'      sha256 "{sums[name]}"',
                "    end",
            ]
        lines += ["  end", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("version", help="the release version, such as 0.1.0")
    parser.add_argument("sums", help="the release's SHA256SUMS file")
    parser.add_argument("--repository", default="x6c-co/age-plugin-rypt")
    parser.add_argument("--base-url", help="where the tarballs are, if not the GitHub release")
    args = parser.parse_args()

    if not re.fullmatch(r"\d+\.\d+\.\d+", args.version):
        sys.exit(f"not a release version: {args.version}")
    if not re.fullmatch(r"[\w.-]+/[\w.-]+", args.repository):
        sys.exit(f"not a GitHub repository: {args.repository}")
    base_url = args.base_url or (
        f"https://github.com/{args.repository}/releases/download/v{args.version}"
    )

    sys.stdout.write(
        FORMULA.substitute(
            repository=args.repository,
            version=args.version,
            platforms=platform_blocks(args.version, read_sums(args.sums), base_url.rstrip("/")),
        )
    )


if __name__ == "__main__":
    main()
